seed: 42
image_size: 224
n_folds: 5
batch_size: 32
num_workers: 0  # 4 pour le kaggle, 0 pour le local
dataset_root: "../dataset"
classes:
  - glioma
  - meningioma
  - notumor
  - pituitary
samples_per_class: 500   # null pour utiliser tout le dataset